ask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('qa.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

qa/urls.py
#URLs for app 'qa'

from django.urls import path
from . import views

app_name = 'qa'
urlpatterns = [
	path('', views.index, name='index'),
	path('question/<int:question_id>/', views.question, name='question'),
	path('ask/', views.ask, name='ask'),
	path('popular/', views.popular, name='popular'),
	path('tagged/<slug:slug>/', views.tagged, name='tagged'),
	path('question_like/', views.question_like, name='question_like'),
	path('answer_like/', views.answer_like, name='answer_like'),
	path('answer_correct/', views.answer_correct, name='answer_correct'),
]

users/urls.py
#URLs for app 'users'

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	path('', include('django.contrib.auth.urls')),
	path('signup/', views.signup, name='signup'),
	path('settings/', views.show_profile, name='show_profile'),
	path('settings/update/', views.update_profile, name='update_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to='avatars/', blank=True)

	def __str__(self):
		return f'{self.user.username}_profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
		instance.profile.save()

users/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['avatar']

	def clean_avatar(self):
		avatar = self.cleaned_data.get('avatar', False)
		if avatar and avatar.size > 1024*1024:
			raise ValidationError("Image size can't exceed 1 MB")
		return avatar

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *

# Create your views here.
def signup(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('qa:index')
    context = {'form': form}
    return render(request, 'signup.html', context)

@login_required
def show_profile(request):
    user=request.user
    profile = get_object_or_404(Profile, user=request.user)
    context = {'user': user, 'profile': profile}
    return render(request, 'show_profile.html', context)

@login_required
def update_profile(request):
    if request.method != 'POST':
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    else:
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('users:show_profile')
    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'update_profile.html', context)

users/templates/show_profile.html
{% extends "base.html" %}

{% block content %}
	<h3 class="mb-3 mt-1">Settings: {{ user.username }}</h2>
	{% if profile.avatar %}
		<div class="avatar-big" style="background-image: url('{{ profile.avatar.url }}');">
        </div>
	{% endif %}
	<p class="my-4"><b>Username:</b> {{ user.username }}<br>
	  <b>Email:</b> {{ user.email }}<br>
	  <b>Date of registration:</b> {{ user.date_joined }}</p>
	<p class="my-4"><a class="btn btn-primary" role="button" href="{% url 'users:update_profile' %}">Edit</a><p>
{% endblock content %}

users/templates/signup.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
	<h3 class="mb-3 mt-1">Registeration of a new user</h2>
	<h5 class="mb-3 mt-1">Enter your login and password</h5>
	<form action="{% url 'users:signup' %}" method='POST'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name='submit' class="btn btn-primary mt-2">Sign up</button>
		{% endbuttons %}
		<input type='hidden' name='next' value="{% url 'qa:index' %}" />
	</form>
{% endblock content %}

users/templates/update_profile.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
	<h3 class="mb-3 mt-1">Edit settings: {{ user.username }}</h2>
	<form action="{% url 'users:update_profile' %}" method='POST' enctype='multipart/form-data'>
		{% csrf_token %}
		{% bootstrap_form user_form %}
		{% if user.profile.avatar %}
			<div class="avatar-big" style="background-image: url('{{ user.profile.avatar.url }}');">
        	</div>
		{% endif %}
		{% bootstrap_form profile_form %}
		{% buttons %}
			<button name='submit' class="btn btn-primary mt-2">Save</button>
		{% endbuttons %}
		<input type='hidden' name='next' value="{% url 'users:show_profile' %}" />
	</form>
{% endblock content %}