ask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('qa.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

qa/urls.py
#URLs for app 'qa'

from django.urls import path
from . import views

app_name = 'qa'
urlpatterns = [
	path('', views.index, name='index'),
	path('question/<int:question_id>/', views.question, name='question'),
	path('ask/', views.ask, name='ask'),
	path('popular/', views.popular, name='popular'),
	path('tagged/<slug:slug>/', views.tagged, name='tagged'),
	path('question_like/', views.question_like, name='question_like'),
	path('answer_like/', views.answer_like, name='answer_like'),
	path('answer_correct/', views.answer_correct, name='answer_correct'),
]

users/urls.py
#URLs for app 'users'

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	path('', include('django.contrib.auth.urls')),
	path('signup/', views.signup, name='signup'),
	path('settings/', views.show_profile, name='show_profile'),
	path('settings/update/', views.update_profile, name='update_profile'),
]

qa/models.py
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
import re

# Create your models here.

class QuestionManager(models.Manager): 
	def new(self):
		return self.order_by('-added_at')

	def popular(self):
		return self.annotate(likes_count=Count('likes')).order_by('-likes_count')

class Question(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	added_at = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
	likes = models.ManyToManyField(User, related_name='question_like_user', blank=True)
	tags = TaggableManager(blank=True)
	objects = QuestionManager()

	def __str__(self):
		return self.title

	def get_url(self):
		return reverse('qa:question', args=[self.id])

class Answer(models.Model):
	text = models.TextField()
	added_at = models.DateTimeField(auto_now_add=True)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
	likes = models.ManyToManyField(User, related_name='answer_like_user', blank=True)
	is_correct = models.BooleanField(default=False)

	def __str__(self):
		return f'answer {self.id}'

qa/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
#from django.core.exceptions import ValidationError
#import re


class AskForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['title', 'text', 'tags']
		labels = {'title': 'Title', 'text': 'Question', 'tags': 'Tags'}
		
"""
class AskForm(forms.Form):
	title = forms.CharField(max_length=255, label="Title")
	text = forms.CharField(widget=forms.Textarea, label="Question")
	tags = forms.CharField(max_length=255, label="Tags", required=False)

	def clean_tags(self):
		tags_string = self.cleaned_data['tags']
		tags_string = tags_string.strip().lower()
		if re.match(r'^[\w\s]*$', tags_string):
			tags=set()
			tags_set = set(tags_string.split())
			for tag in tags_set:
				if not Tag.objects.filter(title=tag).first():
					Tag.objects.create(title=tag)
				tags.add(Tag.objects.get(title=tag))
			return tags
		else:
			raise ValidationError('Use only letters, digits or undercover')
"""

class AnswerForm(forms.ModelForm):
	class Meta:
		model = Answer
		fields = ['text']
		labels = {'text': ''}

		widgets = {
			'text': forms.Textarea(attrs={
				'class' : 'form-control', 
				'placeholder' : 'Give your answer here.',
				})
		}

qa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.paginator import Paginator
from taggit.models import Tag
from .models import *
from .forms import *

def test(request, *args, **kwargs):
    return HttpResponse('OK')

def index(request):
    questions = Question.objects.new()
    limit = request.GET.get('limit', 5)
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, limit)
    paginator.baseurl = '/?page='
    page = paginator.page(page)
    context = {'questions': page.object_list, 'paginator': paginator, 
                'page': page, 'order': 'new'}
    return render(request, 'index.html', context)

def popular (request):
    questions = Question.objects.popular()
    limit = request.GET.get('limit', 5)
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, limit)
    paginator.baseurl = '/popular/?page='
    page = paginator.page(page)
    context = {'questions': page.object_list, 'paginator': paginator, 
                'page': page, 'order': 'popular'}
    return render(request, 'index.html', context)

def tagged (request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    questions = Question.objects.popular().filter(tags=tag)
    limit = request.GET.get('limit', 5)
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, limit)
    paginator.baseurl = f'/tagged/{slug}/?page='
    page = paginator.page(page)
    context = {'questions': page.object_list, 'paginator': paginator, 
                'page': page, 'tag_filter': tag}
    return render(request, 'index.html', context)


def question(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    answers = question.answer_set.order_by('added_at')
    if request.method != 'POST':
        form = AnswerForm()
    else:
        form = AnswerForm(data=request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            url = question.get_url()
            return redirect(url)
    context = {'question': question, 'answers': answers, 'form': form}
    return render(request, 'question.html', context)

@login_required
def ask(request):
    if request.method != 'POST':
        form = AskForm()
    else:
        form = AskForm(data=request.POST)
        if form.is_valid():
            ask = form.save(commit=False)
            ask.author = request.user
            ask.save()
            form.save_m2m()
            url = ask.get_url()
            return redirect(url)
    context = {'form': form}
    return render(request, 'ask.html', context)

@login_required
def question_like(request, **kwargs):
    url_from = request.POST.get('url_from')
    question_id = request.POST.get('question_id')
    question = get_object_or_404(Question, id=question_id)
    if request.method == 'POST':
        user = request.user
        if question.likes.filter(id=user.id):
            question.likes.remove(user)
        else:
            question.likes.add(user)
    return redirect(url_from)

@login_required
def answer_like(request, **kwargs):
    url_from = request.POST.get('url_from')
    answer_id = request.POST.get('answer_id')
    answer = get_object_or_404(Answer, id=answer_id)
    if request.method == 'POST':
        user = request.user
        if answer.likes.filter(id=user.id):
            answer.likes.remove(user)
        else:
            answer.likes.add(user)
    return redirect(url_from)

@login_required
def answer_correct(request, **kwargs):
    answer_id = request.POST.get('answer_id')
    answer = get_object_or_404(Answer, id=answer_id)
    question = answer.question
    if request.method == 'POST' and request.user == question.author:
        answer.is_correct = not answer.is_correct
        answer.save()
    return redirect(question.get_url())

qa/templates/old/old a_like_button.html
<form action="{% url 'qa:answer_like' %}" method='POST'>
	{% csrf_token %}
	<input type='hidden' name='url_from' value='{{ url_from }}'>
	<input type='hidden' name='answer_id' value='{{ answer.id }}'>
	<button name='submit'>
		{% if is_liked %}
			LIKES: 
		{% else %}
			likes: 
		{% endif %}
		{{ likes_count }}
	</button>
</form>

qa/templates/old/old ask.html
{% extends "base.html" %}

{% block content %}
	<p>Ask your question:</p>
	<form action="{% url 'qa:ask' %}" method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Ask</button>
		<input type='hidden' name='next' value="{% url 'qa:index' %}" />
	</form>
{% endblock content %}

qa/templates/old/old base.html
{% load bootstrap5 %}
{% load qa_tags %}
{% load static %}

<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Q&A</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'qa/css/base_style.css' %}">

</head>
<body>
  <nav class="navbar navbar-dark navbar-expand-sm bg-primary">
    <div class="container-xxl">
      <a class="navbar-brand" href="{% url 'qa:index' %}">Q&A</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
      data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'qa:index' %}">Questions</a>
          <a class="nav-link" href="{% url 'qa:ask' %}">Ask!</a>
          {% if user.is_authenticated %}
            <span class="navbar-text">Hello, <b>{{ user.username }}</b></span>
            <a class="nav-link" href="{% url 'users:show_profile' %}">Settings</a>
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          {% else %}
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            <a class="nav-link" href="{% url 'users:signup' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

<!--
	<div><p>
		<a href="{% url 'qa:index' %}">Q&A</a> | 
		<a href="{% url 'qa:ask' %}">Ask!</a> | 
		{% if user.is_authenticated %}
			<span>{{ user.username }}</span> | 
			<a href="{% url 'users:show_profile' %}">Settings</a> | 
			<a href="{% url 'users:logout' %}">Log out</a>
		{% else %}
			<a href="{% url 'users:login' %}">Log in</a> | 
			<a href="{% url 'users:signup' %}">Register</a>
		{% endif %}
	</p></div>
	<hr>
-->
  <div class="container-xxl">
  	<div class="row">
  	  <div class="col-xs-12 col-md-8">
  	  	{% block content %}{% endblock content %}
  	  </div>
  	  <div class="col-xs-12 col-md-4">
  	  	{% show_popular_tags %}
  	  </div>
  	</div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

qa/templates/old/old index.html
{% extends "base.html" %}
{% load likes_options %}

{% block content %}
	<h3>
		{% if order == 'new' %}
			<span>New questions</span>
		{% else %}
			<a href="{% url 'qa:index' %}">New questions</a>
		{% endif %} | 
		{% if order == 'popular' %}
			<span>Hot questions</span>
		{% else %}
			<a href="{% url 'qa:popular' %}">Hot questions</a>
		{% endif %}
	</h3>
	{% if tag_filter %}
		<h2>Filtered by #{{ tag_filter }}</h2>
	{% endif %}
<!--
  {% for question in questions %}
	<div class="card">
      <div class="card-body">
        <h4 class="card-title">
          <a href="{% url 'qa:question' question.id %}" class="card-link">{{ question }}</a>
        </h4>
        <p class="card-text">{{ question.text|truncatewords:50 }}</p>
        <p class="card-text">Answers: {{ question.answer_set.count }}</p>
        {% if question.tags.all %}
		  <p class="card-text">Tags: 
		  	{% for tag in question.tags.all %}
		  	  <span class="badge text-bg-secondary">
		  	    <a href="{% url 'qa:tagged' tag.slug %}">#{{ tag.name }} ></a>
		  	  </span>
		  	{% endfor %}
		  </p>
		{% endif %}  
		{% q_like_button question user.id request.get_full_path %}
      </div>
      <div class="card-footer text-muted text-end">
        by {{ question.author }} | {{ question.added_at }}
      </div>
    </div>
  {% endfor %}
-->

	<ul>
		{% for question in questions %}
			<li><div>
				<h2><a href="{% url 'qa:question' question.id %}">{{ question }}</a></h2>
				<p>{{ question.text|truncatewords:30 }}</p>
				<p>Answers: {{ question.answer_set.count }}</p>
				{% if question.tags.all %}
					<p>Tags: 
						{% for tag in question.tags.all %}
							<a href="{% url 'qa:tagged' tag.slug %}">#{{ tag.name }} ></a>
						{% endfor %}
					</p>
				{% endif %}
				{% q_like_button question user.id request.get_full_path %}
				<p>by {{ question.author }} | {{ question.added_at }}</p>
				<hr>
			</div></li>
		{% endfor %}
	</ul>
-->

	<nav><ul class="paginator">
		{% for p in paginator.page_range %}
			{% if p == page.number %}
				<li class="active">
			{% else %}
				<li>
			{% endif %}
				<a href="{{ paginator.baseurl }}{{ p }}">{{ p }}</a>
			</li>
		{% endfor %}
	</nav></ul>
{% endblock content %}

qa/templates/old/old popular_tags.html
<div>
  <h4>Popular Tags</h4>
  <p>			
  {% for tag in popular_tags %}
  	<span class="badge text-bg-primary">
      <a href="{% url 'qa:tagged' tag.slug %}">{{ tag }}</a> 
    </span>
  {% endfor %}		
  </p>
</div>

qa/templates/old/old q_like_button.html
<form action="{% url 'qa:question_like' %}" method='POST'>
	{% csrf_token %}
	<input type='hidden' name='url_from' value='{{ url_from }}'>
	<input type='hidden' name='question_id' value='{{ question.id }}'>
	<button name='submit' class="btn btn-danger">
		{% if is_liked %}
			LIKES: 
		{% else %}
			likes: 
		{% endif %}
		{{ likes_count }}
	</button>
</form>

<!--
<form action="{% url 'qa:question_like' %}" method='POST'>
	{% csrf_token %}
	<input type='hidden' name='url_from' value='{{ url_from }}'>
	<input type='hidden' name='question_id' value='{{ question.id }}'>
	<button name='submit'>
		{% if is_liked %}
			LIKES: 
		{% else %}
			likes: 
		{% endif %}
		{{ likes_count }}
	</button>
</form>
-->

qa/templates/old/old question.html
{% extends "base.html" %}
{% load likes_options %}

{% block content %}
	<h2>{{ question }}</h2>
	{% if question.tags.all %}
		<p>Tags: 
			{% for tag in question.tags.all %}
				<a href="{% url 'qa:tagged' tag.slug %}">#{{ tag.name }}</a> 
			{% endfor %}
		</p>
	{% endif %}
	<h4>{{ question.text }}</h4>
	{% q_like_button question user.id request.path %}
	<ul>
		{% for answer in answers %}
			<li><p>{{ answer.text }}</p></li>
			{% if answer.is_correct %}
				<h5>It's a correct answer!</h5>
			{% endif %}
			{% a_like_button answer user.id request.path %}
			{% if user == question.author %}
				<form action="{% url 'qa:answer_correct' %}" method='POST'>
					{% csrf_token %}
					<input type='hidden' name='answer_id' value='{{ answer.id }}'>
					<button name='submit'>
						{% if answer.is_correct %}
							Wrong! 
						{% else %}
							Correct! 
						{% endif %}
					</button>
				</form>
			{% endif %}
		{% endfor %}
	</ul>
	{% if user.is_authenticated %}
		<form action="{% url 'qa:question' question.id %}" method='POST'>
			{% csrf_token %}
			{{ form.as_p }}
			<button name='submit'>Send</button>
		</form>
	{% endif %}
{% endblock content %}